### ISSUE TITLE
routergame.php not working i think

### ISSUE THREAD

**Issue by batscs** [Haron123/haron.gay#1]
hewwo :3 i think something is nyot w-wowking with youw woutewgame, i dont w-want t-to sound wude ow (・`ω´・) a-anything, but backgwound *screeches* image seems t-to nyot woad and cuwsow is buggy when *notices buldge* scwowwing the x3 website hm ^w^ idk maybe you c-can fix i-it - w-wouwd weawwy x3 appweciate it, t-t-thanks fow taking youw time and wead this

**Comment by Haron123** [comment]
Oh, i appweciate uw feedback! OwO howevew, evewything seems to be wowking fine on ouww end. Maybe it's juwst a gwitch on uw device. Thanks fow weaching ouwt thouwgh! OwO 😊

**Comment by Haron123** [comment]
Issue closed
